### ISSUE TITLE
First location request after app launch fails (Huawei)

### ISSUE THREAD

**Issue by 0phelia** [stroeer/locator-android#13]
The very first location request after fresh app start usually fails to provide any location data at all when location is initially disabled on a device. It returns "Location not found" instead although the initial call goes through all the necessary stages until an error occurs in `addOnConnectionFailedListener {...}` in `HuaweiSearchDelegate.kt`

**Comment by timobaehr** [comment]
Steps to reproduce:

-     disable location on device via Quick Settings Menu -> Location (this step is not always necessary)
-     launch the app (close if it was in the background since we need fresh restart to reproduce)
-     try to retrieve location
-     enable location when redirected to system location activity
-     error appears instead of correct lat/long values
